image: ubuntu:16.04

stages:
  - test

testing:
    stage: test
    before_script:
      - apt-get clean && apt-get update
      - apt-get install -y cmake make python-dev python-pip
      - pip install numpy unittest2

    script:
      - python setup.py test
