name: Build and test
on:
  push:
    branches: [master, develop]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install packages via apt
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++
    - name: Python setup
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages via pip
      run: pip install numpy pytest
    - name: Build and install
      run: pip install -e .
    - name: Test
      run: pytest -v test
