name: Build and test
on:
  push:
    branches: [master, develop]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install packages via apt
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build and install
      run: pip install .
    - name: Test
      run: |
        pip install .[test]
        pytest -v test
